export const PROCESSING = {
  TARGET_FPS: 30,
  SAMPLE_BUFFER_LIMIT: 900,
  BEAT_BUFFER_LIMIT: 80,
  PUBLISH_THROTTLE_MS: 50,
  // Requisitos mínimos para publicar biomarcadores clínicos.
  MIN_SQI_FOR_VALID: 0.05,
  MIN_PERFUSION_FOR_VALID: 0.08,
  MAX_MOTION_FOR_VALID: 0.35,
  MAX_CLIP_HIGH_FOR_VALID: 0.2,
  MAX_CLIP_LOW_FOR_VALID: 0.2,
  MIN_VALID_BEATS: 5,
  MIN_VALID_RR_COUNT: 4,
  // Histéresis temporal para puerta de evidencia viva.
  EVIDENCE_GOOD_FRAMES_TO_VALIDATE: 18,
  EVIDENCE_BAD_FRAMES_TO_INVALIDATE: 4,
  EVIDENCE_PULSE_HOLD_FRAMES: 24,
  MIN_SQI_QUICK_FOR_BEAT: 0
} as const
